### ISSUE TITLE
PDF not getting saved.

### ISSUE THREAD

**Issue by mustafahasankhan** [chadimessmer/Pay-Your-BIll---MF#1]
Great work mate, but I tried exporting PDF but it doesn't save.
JSON works.

Also please add these two features:

- Add English language
- Add auto receipt number incrementer.

**Comment by chadimessmer** [comment]
Hi Mustafa,

Thanks for your feedback. 
This software is designed to create invoices with QR code following the [Swiss Payment Standards](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf) and will only work with a **swiss IBAN number** (starting with "CH"). 

Are you trying with a non-swiss IBAN ?
If you are trying with a swiss iban, do you have any error message ?
